# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a2a54214ccdc49f445853b2bde2d697"
application_url = "https://administrator-procurement-world-talented.trycloudflare.com"
embedded = true
name = "satim v3"
handle = "satim-v3"

[build]
include_config_on_deploy = true
dev_store_url = "quickstart-d0ba2c9a.myshopify.com"
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://administrator-procurement-world-talented.trycloudflare.com/auth/callback",
  "https://administrator-procurement-world-talented.trycloudflare.com/auth/shopify/callback",
  "https://administrator-procurement-world-talented.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
